name: RCM Daily Bot
on:
  schedule:
    - cron: '45 15 * * 1-4' # 17:45 בישראל
    - cron: '0 21 * * 1-5'  # 23:00 בישראל
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
        
